name: 'mk'
redisConfig:
  host: '1.117.167.166'
  port: 6379
  expire: 300
mysqlConfig:
  Host: 'sh-cynosdbmysql-grp-khzm97cq.sql.tencentcdb.com'
  Port: 27244
  Name: 'mxshop_srv'
  User: 'local'
  Password: 'local181!'
