definitions:
  models.LoginForm:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    type: object
  models.RegisterForm:
    properties:
      code:
        maxLength: 6
        minLength: 6
        type: string
      email:
        type: string
      password:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - code
    - email
    - password
    type: object
  models.UserListForm:
    properties:
      email:
        type: string
      nickName:
        type: string
      pageNo:
        example: 1
        minimum: 0
        type: integer
      pageSize:
        example: 10
        minimum: 0
        type: integer
    required:
    - pageNo
    - pageSize
    type: object
  models.VerificationCodeForm:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  utils.EmptyInfo:
    type: object
  utils.ResponseResultInfo:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /user/getUserList:
    post:
      consumes:
      - application/json
      description: 获取user用户列表
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.UserListForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 获取user用户列表
      tags:
      - user用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登陆
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 用户登陆
      tags:
      - user用户
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 用户注册
      tags:
      - user用户
  /user/sendVerificationCode:
    post:
      consumes:
      - application/json
      description: 发送验证码
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.VerificationCodeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 发送验证码
      tags:
      - user用户
swagger: "2.0"
