definitions:
  article.AllListForm:
    properties:
      classify:
        type: string
      pageNo:
        example: 1
        minimum: 0
        type: integer
      pageSize:
        example: 10
        minimum: 0
        type: integer
      status:
        description: 1草稿 2待审核 3审核未通过 4已发布 5已删除
        example: "1"
        type: string
      tag:
        type: string
      title:
        type: string
    required:
    - pageNo
    - pageSize
    type: object
  article.ReviewForm:
    properties:
      description:
        description: 审核意见
        type: string
      id:
        type: integer
      status:
        description: 3驳回 4通过
        example: "3"
        type: string
    type: object
  article.SaveDraftForm:
    properties:
      classify:
        type: string
      collectionColumn:
        type: string
      content:
        type: string
      coverImg:
        type: string
      id:
        type: integer
      summary:
        type: string
      tags:
        type: string
      title:
        type: string
      userId:
        type: integer
    required:
    - title
    - userId
    type: object
  article.SaveForm:
    properties:
      classify:
        type: string
      collectionColumn:
        type: string
      content:
        type: string
      coverImg:
        type: string
      id:
        type: integer
      summary:
        type: string
      tags:
        type: string
      title:
        type: string
      userId:
        type: integer
    required:
    - classify
    - collectionColumn
    - content
    - coverImg
    - summary
    - tags
    - title
    - userId
    type: object
  article.UserArticleListForm:
    properties:
      pageNo:
        example: 1
        minimum: 0
        type: integer
      pageSize:
        example: 10
        minimum: 0
        type: integer
    required:
    - pageNo
    - pageSize
    type: object
  articleColumn.ReviewForm:
    properties:
      description:
        description: 审核意见
        type: string
      id:
        type: integer
      status:
        description: 2未通过、3已发布
        example: "2"
        type: string
    type: object
  articleColumn.SaveForm:
    properties:
      coverImg:
        type: string
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
    required:
    - introduction
    - name
    type: object
  enum.EnumsForm:
    properties:
      name:
        type: string
      parentId:
        type: string
      typeCode:
        type: string
      typeName:
        type: string
      value:
        type: string
    required:
    - name
    - typeCode
    - typeName
    - value
    type: object
  user.ListForm:
    properties:
      email:
        type: string
      nickName:
        type: string
      pageNo:
        example: 1
        minimum: 0
        type: integer
      pageSize:
        example: 10
        minimum: 0
        type: integer
    required:
    - pageNo
    - pageSize
    type: object
  user.LoginForm:
    properties:
      email:
        example: mk@163.com
        type: string
      password:
        example: "123456"
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    type: object
  user.RegisterForm:
    properties:
      code:
        maxLength: 6
        minLength: 6
        type: string
      email:
        type: string
      password:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - code
    - email
    - password
    type: object
  user.VerificationCodeForm:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  utils.EmptyInfo:
    type: object
  utils.ResponseResultInfo:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    name: API Support
paths:
  /article/getArticleDetails:
    get:
      consumes:
      - application/json
      description: 获取文章详情
      parameters:
      - description: 文章id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取文章详情
      tags:
      - article文章
  /article/getArticleList:
    post:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/article.AllListForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 获取文章列表
      tags:
      - article文章
  /article/getUserArticleList:
    post:
      consumes:
      - application/json
      description: 获取用户文章列表
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/article.UserArticleListForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取用户文章列表
      tags:
      - article文章
  /article/review:
    post:
      consumes:
      - application/json
      description: 文章专栏审核
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/articleColumn.ReviewForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 文章专栏审核
      tags:
      - articleColumn专栏
  /article/save:
    post:
      consumes:
      - application/json
      description: 保存文章
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/article.SaveForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 保存文章
      tags:
      - article文章
  /article/saveDraft:
    post:
      consumes:
      - application/json
      description: 保存草稿
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/article.SaveDraftForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 保存草稿
      tags:
      - article文章
  /articleColumn/delete:
    delete:
      consumes:
      - application/json
      description: 根据id删除专栏
      parameters:
      - description: 专栏id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 根据id删除专栏
      tags:
      - articleColumn专栏
  /articleColumn/details:
    get:
      consumes:
      - application/json
      description: 获取专栏详情
      parameters:
      - description: 专栏id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取专栏详情
      tags:
      - articleColumn专栏
  /articleColumn/getAllArticleColumnList:
    get:
      consumes:
      - application/json
      description: 获取全部专栏
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取全部专栏
      tags:
      - articleColumn专栏
  /articleColumn/save:
    post:
      consumes:
      - application/json
      description: 保存专栏
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/articleColumn.SaveForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 保存专栏
      tags:
      - articleColumn专栏
  /enum/delete:
    delete:
      consumes:
      - application/json
      description: 根据id删除指定枚举
      parameters:
      - description: 枚举id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 根据id删除指定枚举
      tags:
      - enum枚举
  /enum/details:
    get:
      consumes:
      - application/json
      description: 获取枚举详情
      parameters:
      - description: 枚举id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取枚举详情
      tags:
      - enum枚举
  /enum/getAllEnums:
    get:
      consumes:
      - application/json
      description: 获取全部数据
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取全部数据
      tags:
      - enum枚举
  /enum/getEnumsByType:
    get:
      consumes:
      - application/json
      description: 根据分类查询枚举
      parameters:
      - description: 枚举类型code
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 根据分类查询枚举
      tags:
      - enum枚举
  /enum/save:
    post:
      consumes:
      - application/json
      description: 增加、编辑
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/enum.EnumsForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 增加、编辑
      tags:
      - enum枚举
  /file/upload:
    post:
      consumes:
      - application/json
      description: 文件上传
      parameters:
      - description: 请求对象
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 文件上传
      tags:
      - file文件
  /user/getUserDetails:
    get:
      consumes:
      - application/json
      description: 获取用户详情
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取用户详情
      tags:
      - user用户
  /user/getUserList:
    post:
      consumes:
      - application/json
      description: 获取user用户列表
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/user.ListForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取user用户列表
      tags:
      - user用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登陆
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/user.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 用户登陆
      tags:
      - user用户
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/user.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 用户注册
      tags:
      - user用户
  /user/sendVerificationCode:
    post:
      consumes:
      - application/json
      description: 发送验证码
      parameters:
      - description: 请求对象
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/user.VerificationCodeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseResultInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.EmptyInfo'
      summary: 发送验证码
      tags:
      - user用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
